In [336]:
import numpy as np

In [337]:
%load_ext autoreload
%autoreload 2
from MaxPlus import MaxPlus


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [338]:
A = MaxPlus([[MaxPlus.Zero,5,3],[4,3,4],[6,5,4]])
A

[[-inf   5.   3.]
 [  4.   3.   4.]
 [  6.   5.   4.]]

In [ ]:
B = MaxPlus.zeros((3,3))
B

AttributeError: type object 'MaxPlus' has no attribute 'zero'

In [ ]:
C = MaxPlus.eye(3)
C

[[  0. -inf -inf]
 [-inf   0. -inf]
 [-inf -inf   0.]]

In [ ]:
A+C

[[0. 5. 3.]
 [4. 3. 4.]
 [6. 5. 4.]]

In [ ]:
A@B

[[-inf -inf -inf]
 [-inf -inf -inf]
 [-inf -inf -inf]]

In [ ]:
MaxPlus.ones((2,2))

[[0. 0.]
 [0. 0.]]

In [ ]:
A@A

[[ 9.  8.  9.]
 [10.  9.  8.]
 [10. 11.  9.]]

In [ ]:
A**2

[[ 9.  8.  9.]
 [10.  9.  8.]
 [10. 11.  9.]]

In [ ]:
MaxPlus.naiveeigenv(MaxPlus(1))

1.0

In [ ]:
MaxPlus.naiveeigenv(MaxPlus.zero())

-inf

In [ ]:
MaxPlus.naiveeigenv(MaxPlus.top())

inf

In [ ]:
A = MaxPlus([[MaxPlus.Zero,5,3],[4,3,4],[6,5,4]])
A

[[-inf   5.   3.]
 [  4.   3.   4.]
 [  6.   5.   4.]]

In [ ]:
MaxPlus.naiveeigenv(A)

5.0

In [ ]:
M = MaxPlus.zero()
M

[[-inf]]

In [ ]:
M = A*(-MaxPlus.naiveeigenv(A))
M

[[-inf   0.  -2.]
 [ -1.  -2.  -1.]
 [  1.   0.  -1.]]

In [ ]:
Mplus = MaxPlus.plus(M)
Mplus

[[ 0.  0. -1.]
 [ 0.  0. -1.]
 [ 1.  1.  0.]]

In [ ]:
x = Mplus[:,0:1]
x

array([[0.],
       [0.],
       [1.]])

In [ ]:
v,rho = MaxPlus.eigenspace(A)
print(v,rho)

[[0.]
 [0.]
 [1.]] 5.0


In [ ]:
A = MaxPlus([[1.7,2.1],[1.2,2.7]])

b = MaxPlus([[2.6],[3.2]])
xmin = MaxPlus.astarb(A,b)

A//b


[[0.9 0.5]]

In [ ]:
A0 = MaxPlus([[MaxPlus],[],[]])

In [ ]:
# 4 train

A4 = MaxPlus([[2,5],[3,3]])
A5 = MaxPlus([[2,5,MaxPlus.Zero],[MaxPlus.Zero,3,3],[MaxPlus.Unit,MaxPlus.Zero,MaxPlus.Zero]])
A52 = MaxPlus([[2,5,MaxPlus.Zero],[3,MaxPlus.Zero,3],[MaxPlus.Zero,MaxPlus.Unit,MaxPlus.Zero]])
A6 = MaxPlus([[2,5,MaxPlus.Zero,MaxPlus.Zero],
              [MaxPlus.Zero,MaxPlus.Zero,3,3],
              [MaxPlus.Unit,MaxPlus.Zero,MaxPlus.Zero,MaxPlus.Zero],
              [MaxPlus.Zero,MaxPlus.Unit,MaxPlus.Zero,MaxPlus.Zero]
              ])
lambda4 = MaxPlus.naiveeigenv(A4)
lambda5 = MaxPlus.naiveeigenv(A5)
lambda52 = MaxPlus.naiveeigenv(A52)
lambda6 = MaxPlus.naiveeigenv(A6)
print(lambda4,lambda5,lambda52,lambda6)

4.0 3.0 4.0 2.6666666666666665
